sp = 3;
hs = 4;
vs = -2;
sc = 3.66;
timer = 0;
action_move_to(-96-hs*200, 560-vs*200);
rotsp = 0;
angle = 0;
lul = 0;
surf = -1;
room_speed=60;
planeShadowSprite = sprite_duplicate(sprPlaneShadow2);
var planeShadowAlpha = sprite_duplicate(sprPlaneShadow1);
sprite_set_alpha_from_sprite(planeShadowSprite, planeShadowAlpha);
sprite_delete(planeShadowAlpha);
__view_set( e__VW.XView, 0, 0 );
__view_set( e__VW.YView, 0, 0 );
freq=0.1;
soundvolume(global.sndEngine,0.9);
prop = 0;
tailImg = 0;
ku = 1;
vol = 1;
fuu = 1;
make = 0;
