function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // objMenu
	global.__objectDepths[1] = 0; // objMenuAir
	global.__objectDepths[2] = -11; // objBorderMenu
	global.__objectDepths[3] = -5; // objMenuCreds
	global.__objectDepths[4] = 100; // makestairs
	global.__objectDepths[5] = 0; // stair
	global.__objectDepths[6] = 0; // objStairTails
	global.__objectDepths[7] = -3; // objBGStairs
	global.__objectDepths[8] = 0; // BottomFloor
	global.__objectDepths[9] = -10; // objScratch
	global.__objectDepths[10] = 0; // presentation
	global.__objectDepths[11] = 0; // objTouchControls
	global.__objectDepths[12] = 10001; // controlbg
	global.__objectDepths[13] = -10001; // objectfg
	global.__objectDepths[14] = -10002; // objRingCounter
	global.__objectDepths[15] = 0; // movable
	global.__objectDepths[16] = 0; // engines
	global.__objectDepths[17] = 0; // robot
	global.__objectDepths[18] = 0; // objcore1
	global.__objectDepths[19] = 2; // objcore2
	global.__objectDepths[20] = 10; // objtornado1
	global.__objectDepths[21] = 10; // objtornado2
	global.__objectDepths[22] = -1; // objJaw
	global.__objectDepths[23] = -2; // chopper
	global.__objectDepths[24] = 0; // objJawCollider
	global.__objectDepths[25] = -9; // objJawWeakpoint
	global.__objectDepths[26] = -11; // objCleanCrack
	global.__objectDepths[27] = 0; // objVat
	global.__objectDepths[28] = 0; // objEmptyVat
	global.__objectDepths[29] = 10; // objElevator
	global.__objectDepths[30] = -12; // objLavaBlob
	global.__objectDepths[31] = -10; // objLava
	global.__objectDepths[32] = -11; // objLavaWave
	global.__objectDepths[33] = 2; // objLavaWheel
	global.__objectDepths[34] = 4; // objLavaGirder
	global.__objectDepths[35] = 11; // objlavarockbg
	global.__objectDepths[36] = -14; // objLavaFader
	global.__objectDepths[37] = -4; // objJumpingBlob
	global.__objectDepths[38] = 0; // objBlobSpawner
	global.__objectDepths[39] = -6; // objFloater
	global.__objectDepths[40] = -1; // objFragile
	global.__objectDepths[41] = 0; // objdollbot
	global.__objectDepths[42] = 2; // objdoll
	global.__objectDepths[43] = 0; // objwire
	global.__objectDepths[44] = 0; // objtdl
	global.__objectDepths[45] = 0; // objtdr
	global.__objectDepths[46] = 0; // objooze
	global.__objectDepths[47] = 2; // objooze3
	global.__objectDepths[48] = -1; // objblackboil
	global.__objectDepths[49] = 3; // objdollghost
	global.__objectDepths[50] = 5; // objentangle1
	global.__objectDepths[51] = -1; // objentangle2
	global.__objectDepths[52] = 0; // objblackbubble
	global.__objectDepths[53] = 0; // objHangCore
	global.__objectDepths[54] = 0; // objCraft1
	global.__objectDepths[55] = 1; // objCraft2
	global.__objectDepths[56] = 0; // objPanjan1
	global.__objectDepths[57] = 0; // objBallHolder
	global.__objectDepths[58] = 0; // objHangChain
	global.__objectDepths[59] = 1; // objMechanicCart
	global.__objectDepths[60] = 2; // objAggregate
	global.__objectDepths[61] = 2; // objToolBox
	global.__objectDepths[62] = 2; // objBallCart
	global.__objectDepths[63] = -1; // objMiniGunGround
	global.__objectDepths[64] = 9; // objCavityLight
	global.__objectDepths[65] = -10; // objInstaDie
	global.__objectDepths[66] = -2; // doom
	global.__objectDepths[67] = -3; // objFinalOuter
	global.__objectDepths[68] = -6; // objEggMid
	global.__objectDepths[69] = 0; // static
	global.__objectDepths[70] = 0; // objBridgeCut
	global.__objectDepths[71] = 10; // objFinalRail
	global.__objectDepths[72] = 4; // objDoomKnife
	global.__objectDepths[73] = 4; // objDoomGun
	global.__objectDepths[74] = 4; // objDoomShock
	global.__objectDepths[75] = 4; // objDoomWave
	global.__objectDepths[76] = 2; // objDoomRack
	global.__objectDepths[77] = 0; // objRoxxorz
	global.__objectDepths[78] = -10; // objRockWarning
	global.__objectDepths[79] = -4; // objFinalCrack
	global.__objectDepths[80] = 0; // objOrbitEmerald
	global.__objectDepths[81] = 0; // objLoseEmerald
	global.__objectDepths[82] = 0; // objEvEgg1
	global.__objectDepths[83] = 9000; // objDarkDepths
	global.__objectDepths[84] = 0; // objVent
	global.__objectDepths[85] = -101; // objDeath
	global.__objectDepths[86] = -10; // objassessment
	global.__objectDepths[87] = -4; // objTarget
	global.__objectDepths[88] = 0; // objRamEgg
	global.__objectDepths[89] = 0; // objfallring
	global.__objectDepths[90] = 0; // objring
	global.__objectDepths[91] = 0; // objringget
	global.__objectDepths[92] = 0; // objGetSuper
	global.__objectDepths[93] = 0; // sonic
	global.__objectDepths[94] = 0; // objtails1
	global.__objectDepths[95] = 0; // objtails2
	global.__objectDepths[96] = 0; // objtails3
	global.__objectDepths[97] = 0; // objTails
	global.__objectDepths[98] = 0; // objMoveLogger
	global.__objectDepths[99] = 0; // objRiseWing
	global.__objectDepths[100] = 10; // cam
	global.__objectDepths[101] = 0; // objGrass
	global.__objectDepths[102] = -2; // objFogDust
	global.__objectDepths[103] = -3; // objCraft
	global.__objectDepths[104] = -10; // overlay
	global.__objectDepths[105] = 0; // objJumpingSonic
	global.__objectDepths[106] = 0; // objEggRoll
	global.__objectDepths[107] = 0; // objLinePlode
	global.__objectDepths[108] = 0; // objFaceExplosion
	global.__objectDepths[109] = 0; // objNukeExplosion
	global.__objectDepths[110] = 0; // objPowerSurround
	global.__objectDepths[111] = -6; // objStaticSurround
	global.__objectDepths[112] = -9; // objRiseAura
	global.__objectDepths[113] = -3; // objDarkSmoke
	global.__objectDepths[114] = -2; // objEggHit
	global.__objectDepths[115] = 0; // objSonic
	global.__objectDepths[116] = 0; // objCails
	global.__objectDepths[117] = -7; // objDiscExpand
	global.__objectDepths[118] = 0; // ult_balls
	global.__objectDepths[119] = 0; // ult_bouncer
	global.__objectDepths[120] = 3; // sonails
	global.__objectDepths[121] = 0; // rotBlock
	global.__objectDepths[122] = 1; // fragileBlock
	global.__objectDepths[123] = 1; // transBlock
	global.__objectDepths[124] = 0; // ult_fraction
	global.__objectDepths[125] = 0; // trans_fraction
	global.__objectDepths[126] = 0; // uline
	global.__objectDepths[127] = 0; // upoint
	global.__objectDepths[128] = -3; // objInGameWing
	global.__objectDepths[129] = -10; // objHaloBreak
	global.__objectDepths[130] = -4; // objRean
	global.__objectDepths[131] = 0; // objReanAura
	global.__objectDepths[132] = 0; // objReanGhosting
	global.__objectDepths[133] = 0; // ult_chargeBalls
	global.__objectDepths[134] = 0; // objHaloPieces
	global.__objectDepths[135] = 0; // objNormalEggFall
	global.__objectDepths[136] = -20; // objUltima
	global.__objectDepths[137] = 100; // uctrl
	global.__objectDepths[138] = -100; // ufore
	global.__objectDepths[139] = 99; // ubgline
	global.__objectDepths[140] = 50; // tinyBlock
	global.__objectDepths[141] = 10; // objUltSmoke
	global.__objectDepths[142] = 0; // objDreamTails
	global.__objectDepths[143] = 1; // objEggHand
	global.__objectDepths[144] = 0; // objDreamDoor
	global.__objectDepths[145] = 100; // objDreamCircle
	global.__objectDepths[146] = 101; // objDreamWiggle
	global.__objectDepths[147] = 101; // objDreamTile
	global.__objectDepths[148] = 200; // objmogusbg
	global.__objectDepths[149] = 0; // objTakeOff
	global.__objectDepths[150] = 0; // objTakeOffSmoke
	global.__objectDepths[151] = 4; // objTornadoLanded
	global.__objectDepths[152] = 3; // objTailsPolish
	global.__objectDepths[153] = 0; // objShowOffRocket
	global.__objectDepths[154] = 0; // objShowOffMachine
	global.__objectDepths[155] = 0; // objFlashG1
	global.__objectDepths[156] = -9; // objFlashG2
	global.__objectDepths[157] = 3; // objPushSwitch
	global.__objectDepths[158] = -2; // objStandSwitch
	global.__objectDepths[159] = -2; // line
	global.__objectDepths[160] = -2; // verySpecialLine
	global.__objectDepths[161] = -2; // movingline
	global.__objectDepths[162] = -2; // reportingline
	global.__objectDepths[163] = 0; // point
	global.__objectDepths[164] = 0; // endpoint
	global.__objectDepths[165] = 0; // movingball
	global.__objectDepths[166] = 0; // movingsector
	global.__objectDepths[167] = -1; // grassline
	global.__objectDepths[168] = -2; // rockline
	global.__objectDepths[169] = -2; // grassline2
	global.__objectDepths[170] = -1; // metaline
	global.__objectDepths[171] = -1; // metaside
	global.__objectDepths[172] = -10; // cleanline
	global.__objectDepths[173] = -1; // upground
	global.__objectDepths[174] = 6; // makeStartHut
	global.__objectDepths[175] = -12; // transitiongenerator
	global.__objectDepths[176] = 0; // zerogenerator
	global.__objectDepths[177] = 20; // grassgenerator
	global.__objectDepths[178] = -40; // tutorialgenerator
	global.__objectDepths[179] = 0; // finalgenerator
	global.__objectDepths[180] = 0; // supergenerator
	global.__objectDepths[181] = 0; // panjan
	global.__objectDepths[182] = 0; // objPanjanCore
	global.__objectDepths[183] = 0; // objBot
	global.__objectDepths[184] = 10; // tornado
	global.__objectDepths[185] = 20; // objWaterBack
	global.__objectDepths[186] = -2; // objSplash
	global.__objectDepths[187] = 1; // objSplash2
	global.__objectDepths[188] = -20; // objWaterFront
	global.__objectDepths[189] = -1; // sandline
	global.__objectDepths[190] = -1; // upsand
	global.__objectDepths[191] = 0; // objBotShieldFail
	global.__objectDepths[192] = 0; // objSandRock
	global.__objectDepths[193] = 0; // objSpike
	global.__objectDepths[194] = 0; // objBoostPad
	global.__objectDepths[195] = -10; // objGetOn
	global.__objectDepths[196] = 0; // objFireWall
	global.__objectDepths[197] = 5; // objTunnel
	global.__objectDepths[198] = 0; // objBubbler
	global.__objectDepths[199] = 0; // objBubbleGone
	global.__objectDepths[200] = 0; // objBubble
	global.__objectDepths[201] = -1; // objFish
	global.__objectDepths[202] = 2; // dLine
	global.__objectDepths[203] = 9; // objCaveDrawer
	global.__objectDepths[204] = 0; // drill
	global.__objectDepths[205] = 0; // objTotem
	global.__objectDepths[206] = 0; // objSmallMine
	global.__objectDepths[207] = 10; // objTri
	global.__objectDepths[208] = 0; // objDrillParticle
	global.__objectDepths[209] = 0; // objdoormaker
	global.__objectDepths[210] = 0; // objdoormaker2
	global.__objectDepths[211] = 4; // objdoormaker3
	global.__objectDepths[212] = -1; // greatside
	global.__objectDepths[213] = 0; // greatbrown
	global.__objectDepths[214] = 0; // greatbrown2
	global.__objectDepths[215] = 0; // greatbrown3
	global.__objectDepths[216] = 10; // greattexture
	global.__objectDepths[217] = 0; // objspecialgitta
	global.__objectDepths[218] = 0; // objbouncer
	global.__objectDepths[219] = 0; // objbullet
	global.__objectDepths[220] = 0; // objdashfish
	global.__objectDepths[221] = 0; // objdebris
	global.__objectDepths[222] = -2; // partialdebris
	global.__objectDepths[223] = 0; // objdebrisbouncer
	global.__objectDepths[224] = 0; // objspark
	global.__objectDepths[225] = -1; // objsmoke
	global.__objectDepths[226] = 0; // objsmexp
	global.__objectDepths[227] = 0; // objAirOut
	global.__objectDepths[228] = 0; // objElExp
	global.__objectDepths[229] = 0; // objmedexp
	global.__objectDepths[230] = 0; // objbigexp
	global.__objectDepths[231] = 0; // objredwarning
	global.__objectDepths[232] = 0; // objelectric
	global.__objectDepths[233] = 0; // objsmoker
	global.__objectDepths[234] = 0; // objStatic
	global.__objectDepths[235] = -5; // objCutFlash
	global.__objectDepths[236] = 0; // objredlaser
	global.__objectDepths[237] = 0; // objredblob
	global.__objectDepths[238] = 0; // objredwave
	global.__objectDepths[239] = -5; // objPipe
	global.__objectDepths[240] = -3; // objPipeInit
	global.__objectDepths[241] = -2; // objPipeFollower
	global.__objectDepths[242] = -8; // objLavaFall
	global.__objectDepths[243] = -11; // objLavaDrops
	global.__objectDepths[244] = 0; // sparkables
	global.__objectDepths[245] = 15; // objTDRoom
	global.__objectDepths[246] = -1; // objTDWalls
	global.__objectDepths[247] = 10; // objCpuTable
	global.__objectDepths[248] = 9; // objCpu
	global.__objectDepths[249] = 10; // objServer
	global.__objectDepths[250] = 8; // objMouse
	global.__objectDepths[251] = 9; // objRack
	global.__objectDepths[252] = 8; // objEquipRack
	global.__objectDepths[253] = 12; // objCables1
	global.__objectDepths[254] = 12; // objCables2
	global.__objectDepths[255] = 14; // objSockets
	global.__objectDepths[256] = 5; // objElArc
	global.__objectDepths[257] = 6; // objElSpark
	global.__objectDepths[258] = -10000; // objSuperFG
	global.__objectDepths[259] = 0; // objProxyEgg
	global.__objectDepths[260] = -2; // objSuperEgg
	global.__objectDepths[261] = -1; // objSuperSonic
	global.__objectDepths[262] = 0; // objChargeBalls
	global.__objectDepths[263] = 0; // objEvilChargeBalls
	global.__objectDepths[264] = 0; // objSparkly
	global.__objectDepths[265] = 0; // objFullSparkly
	global.__objectDepths[266] = -3; // objSuperGrass
	global.__objectDepths[267] = -3; // objLimitedGrass
	global.__objectDepths[268] = 0; // objDust
	global.__objectDepths[269] = 0; // objFullDust
	global.__objectDepths[270] = 0; // objCraft3
	global.__objectDepths[271] = 0; // objSuprectile
	global.__objectDepths[272] = -3; // objSuperExplosion
	global.__objectDepths[273] = -1; // objNuke
	global.__objectDepths[274] = -4; // objSuperHit
	global.__objectDepths[275] = -2; // objElectricWall
	global.__objectDepths[276] = -2; // objElectricWarning
	global.__objectDepths[277] = 0; // objSuperRingGet
	global.__objectDepths[278] = 0; // objSuperRing
	global.__objectDepths[279] = -10; // objRainEnd
	global.__objectDepths[280] = 0; // objFrontEnd
	global.__objectDepths[281] = 1; // objSmokeEnd
	global.__objectDepths[282] = -1; // objSonicEnd1
	global.__objectDepths[283] = -2; // objTailsEnd1
	global.__objectDepths[284] = 0; // objBubbleEnd
	global.__objectDepths[285] = 2; // makeDance
	global.__objectDepths[286] = 0; // danceTa
	global.__objectDepths[287] = 0; // danceSo
	global.__objectDepths[288] = 0; // danceStatic
	global.__objectDepths[289] = -1; // objFirePlace
	global.__objectDepths[290] = 0; // objSingleRain
	global.__objectDepths[291] = 0; // objRainHit
	global.__objectDepths[292] = -100; // objEggGanon
	global.__objectDepths[293] = 1; // balls
	global.__objectDepths[294] = -1; // mtline
	global.__objectDepths[295] = 0; // bike
	global.__objectDepths[296] = 0; // objIntroHurt
	global.__objectDepths[297] = 0; // objIntroSonic
	global.__objectDepths[298] = 0; // objIntroEmerald
	global.__objectDepths[299] = -100; // introgenerator
	global.__objectDepths[300] = 0; // objBkSquare
	global.__objectDepths[301] = 0; // mtpoint
	global.__objectDepths[302] = 0; // fakebike
	global.__objectDepths[303] = 100; // objBG
	global.__objectDepths[304] = 90; // objBolt
	global.__objectDepths[305] = 90; // objBranch
	global.__objectDepths[306] = 0; // objCloudMaker
	global.__objectDepths[307] = 91; // objCloud
	global.__objectDepths[308] = -2; // viper
	global.__objectDepths[309] = 0; // objVipFlame
	global.__objectDepths[310] = 0; // objVipRocket
	global.__objectDepths[311] = 0; // objIntroRing
	global.__objectDepths[312] = -1000; // objTuText
	global.__objectDepths[313] = -1000; // objQuitWarning


	global.__objectNames[0] = "objMenu";
	global.__objectNames[1] = "objMenuAir";
	global.__objectNames[2] = "objBorderMenu";
	global.__objectNames[3] = "objMenuCreds";
	global.__objectNames[4] = "makestairs";
	global.__objectNames[5] = "stair";
	global.__objectNames[6] = "objStairTails";
	global.__objectNames[7] = "objBGStairs";
	global.__objectNames[8] = "BottomFloor";
	global.__objectNames[9] = "objScratch";
	global.__objectNames[10] = "presentation";
	global.__objectNames[11] = "objTouchControls";
	global.__objectNames[12] = "controlbg";
	global.__objectNames[13] = "objectfg";
	global.__objectNames[14] = "objRingCounter";
	global.__objectNames[15] = "movable";
	global.__objectNames[16] = "engines";
	global.__objectNames[17] = "robot";
	global.__objectNames[18] = "objcore1";
	global.__objectNames[19] = "objcore2";
	global.__objectNames[20] = "objtornado1";
	global.__objectNames[21] = "objtornado2";
	global.__objectNames[22] = "objJaw";
	global.__objectNames[23] = "chopper";
	global.__objectNames[24] = "objJawCollider";
	global.__objectNames[25] = "objJawWeakpoint";
	global.__objectNames[26] = "objCleanCrack";
	global.__objectNames[27] = "objVat";
	global.__objectNames[28] = "objEmptyVat";
	global.__objectNames[29] = "objElevator";
	global.__objectNames[30] = "objLavaBlob";
	global.__objectNames[31] = "objLava";
	global.__objectNames[32] = "objLavaWave";
	global.__objectNames[33] = "objLavaWheel";
	global.__objectNames[34] = "objLavaGirder";
	global.__objectNames[35] = "objlavarockbg";
	global.__objectNames[36] = "objLavaFader";
	global.__objectNames[37] = "objJumpingBlob";
	global.__objectNames[38] = "objBlobSpawner";
	global.__objectNames[39] = "objFloater";
	global.__objectNames[40] = "objFragile";
	global.__objectNames[41] = "objdollbot";
	global.__objectNames[42] = "objdoll";
	global.__objectNames[43] = "objwire";
	global.__objectNames[44] = "objtdl";
	global.__objectNames[45] = "objtdr";
	global.__objectNames[46] = "objooze";
	global.__objectNames[47] = "objooze3";
	global.__objectNames[48] = "objblackboil";
	global.__objectNames[49] = "objdollghost";
	global.__objectNames[50] = "objentangle1";
	global.__objectNames[51] = "objentangle2";
	global.__objectNames[52] = "objblackbubble";
	global.__objectNames[53] = "objHangCore";
	global.__objectNames[54] = "objCraft1";
	global.__objectNames[55] = "objCraft2";
	global.__objectNames[56] = "objPanjan1";
	global.__objectNames[57] = "objBallHolder";
	global.__objectNames[58] = "objHangChain";
	global.__objectNames[59] = "objMechanicCart";
	global.__objectNames[60] = "objAggregate";
	global.__objectNames[61] = "objToolBox";
	global.__objectNames[62] = "objBallCart";
	global.__objectNames[63] = "objMiniGunGround";
	global.__objectNames[64] = "objCavityLight";
	global.__objectNames[65] = "objInstaDie";
	global.__objectNames[66] = "doom";
	global.__objectNames[67] = "objFinalOuter";
	global.__objectNames[68] = "objEggMid";
	global.__objectNames[69] = "static";
	global.__objectNames[70] = "objBridgeCut";
	global.__objectNames[71] = "objFinalRail";
	global.__objectNames[72] = "objDoomKnife";
	global.__objectNames[73] = "objDoomGun";
	global.__objectNames[74] = "objDoomShock";
	global.__objectNames[75] = "objDoomWave";
	global.__objectNames[76] = "objDoomRack";
	global.__objectNames[77] = "objRoxxorz";
	global.__objectNames[78] = "objRockWarning";
	global.__objectNames[79] = "objFinalCrack";
	global.__objectNames[80] = "objOrbitEmerald";
	global.__objectNames[81] = "objLoseEmerald";
	global.__objectNames[82] = "objEvEgg1";
	global.__objectNames[83] = "objDarkDepths";
	global.__objectNames[84] = "objVent";
	global.__objectNames[85] = "objDeath";
	global.__objectNames[86] = "objassessment";
	global.__objectNames[87] = "objTarget";
	global.__objectNames[88] = "objRamEgg";
	global.__objectNames[89] = "objfallring";
	global.__objectNames[90] = "objring";
	global.__objectNames[91] = "objringget";
	global.__objectNames[92] = "objGetSuper";
	global.__objectNames[93] = "sonic";
	global.__objectNames[94] = "objtails1";
	global.__objectNames[95] = "objtails2";
	global.__objectNames[96] = "objtails3";
	global.__objectNames[97] = "objTails";
	global.__objectNames[98] = "objMoveLogger";
	global.__objectNames[99] = "objRiseWing";
	global.__objectNames[100] = "cam";
	global.__objectNames[101] = "objGrass";
	global.__objectNames[102] = "objFogDust";
	global.__objectNames[103] = "objCraft";
	global.__objectNames[104] = "overlay";
	global.__objectNames[105] = "objJumpingSonic";
	global.__objectNames[106] = "objEggRoll";
	global.__objectNames[107] = "objLinePlode";
	global.__objectNames[108] = "objFaceExplosion";
	global.__objectNames[109] = "objNukeExplosion";
	global.__objectNames[110] = "objPowerSurround";
	global.__objectNames[111] = "objStaticSurround";
	global.__objectNames[112] = "objRiseAura";
	global.__objectNames[113] = "objDarkSmoke";
	global.__objectNames[114] = "objEggHit";
	global.__objectNames[115] = "objSonic";
	global.__objectNames[116] = "objCails";
	global.__objectNames[117] = "objDiscExpand";
	global.__objectNames[118] = "ult_balls";
	global.__objectNames[119] = "ult_bouncer";
	global.__objectNames[120] = "sonails";
	global.__objectNames[121] = "rotBlock";
	global.__objectNames[122] = "fragileBlock";
	global.__objectNames[123] = "transBlock";
	global.__objectNames[124] = "ult_fraction";
	global.__objectNames[125] = "trans_fraction";
	global.__objectNames[126] = "uline";
	global.__objectNames[127] = "upoint";
	global.__objectNames[128] = "objInGameWing";
	global.__objectNames[129] = "objHaloBreak";
	global.__objectNames[130] = "objRean";
	global.__objectNames[131] = "objReanAura";
	global.__objectNames[132] = "objReanGhosting";
	global.__objectNames[133] = "ult_chargeBalls";
	global.__objectNames[134] = "objHaloPieces";
	global.__objectNames[135] = "objNormalEggFall";
	global.__objectNames[136] = "objUltima";
	global.__objectNames[137] = "uctrl";
	global.__objectNames[138] = "ufore";
	global.__objectNames[139] = "ubgline";
	global.__objectNames[140] = "tinyBlock";
	global.__objectNames[141] = "objUltSmoke";
	global.__objectNames[142] = "objDreamTails";
	global.__objectNames[143] = "objEggHand";
	global.__objectNames[144] = "objDreamDoor";
	global.__objectNames[145] = "objDreamCircle";
	global.__objectNames[146] = "objDreamWiggle";
	global.__objectNames[147] = "objDreamTile";
	global.__objectNames[148] = "objmogusbg";
	global.__objectNames[149] = "objTakeOff";
	global.__objectNames[150] = "objTakeOffSmoke";
	global.__objectNames[151] = "objTornadoLanded";
	global.__objectNames[152] = "objTailsPolish";
	global.__objectNames[153] = "objShowOffRocket";
	global.__objectNames[154] = "objShowOffMachine";
	global.__objectNames[155] = "objFlashG1";
	global.__objectNames[156] = "objFlashG2";
	global.__objectNames[157] = "objPushSwitch";
	global.__objectNames[158] = "objStandSwitch";
	global.__objectNames[159] = "line";
	global.__objectNames[160] = "verySpecialLine";
	global.__objectNames[161] = "movingline";
	global.__objectNames[162] = "reportingline";
	global.__objectNames[163] = "point";
	global.__objectNames[164] = "endpoint";
	global.__objectNames[165] = "movingball";
	global.__objectNames[166] = "movingsector";
	global.__objectNames[167] = "grassline";
	global.__objectNames[168] = "rockline";
	global.__objectNames[169] = "grassline2";
	global.__objectNames[170] = "metaline";
	global.__objectNames[171] = "metaside";
	global.__objectNames[172] = "cleanline";
	global.__objectNames[173] = "upground";
	global.__objectNames[174] = "makeStartHut";
	global.__objectNames[175] = "transitiongenerator";
	global.__objectNames[176] = "zerogenerator";
	global.__objectNames[177] = "grassgenerator";
	global.__objectNames[178] = "tutorialgenerator";
	global.__objectNames[179] = "finalgenerator";
	global.__objectNames[180] = "supergenerator";
	global.__objectNames[181] = "panjan";
	global.__objectNames[182] = "objPanjanCore";
	global.__objectNames[183] = "objBot";
	global.__objectNames[184] = "tornado";
	global.__objectNames[185] = "objWaterBack";
	global.__objectNames[186] = "objSplash";
	global.__objectNames[187] = "objSplash2";
	global.__objectNames[188] = "objWaterFront";
	global.__objectNames[189] = "sandline";
	global.__objectNames[190] = "upsand";
	global.__objectNames[191] = "objBotShieldFail";
	global.__objectNames[192] = "objSandRock";
	global.__objectNames[193] = "objSpike";
	global.__objectNames[194] = "objBoostPad";
	global.__objectNames[195] = "objGetOn";
	global.__objectNames[196] = "objFireWall";
	global.__objectNames[197] = "objTunnel";
	global.__objectNames[198] = "objBubbler";
	global.__objectNames[199] = "objBubbleGone";
	global.__objectNames[200] = "objBubble";
	global.__objectNames[201] = "objFish";
	global.__objectNames[202] = "dLine";
	global.__objectNames[203] = "objCaveDrawer";
	global.__objectNames[204] = "drill";
	global.__objectNames[205] = "objTotem";
	global.__objectNames[206] = "objSmallMine";
	global.__objectNames[207] = "objTri";
	global.__objectNames[208] = "objDrillParticle";
	global.__objectNames[209] = "objdoormaker";
	global.__objectNames[210] = "objdoormaker2";
	global.__objectNames[211] = "objdoormaker3";
	global.__objectNames[212] = "greatside";
	global.__objectNames[213] = "greatbrown";
	global.__objectNames[214] = "greatbrown2";
	global.__objectNames[215] = "greatbrown3";
	global.__objectNames[216] = "greattexture";
	global.__objectNames[217] = "objspecialgitta";
	global.__objectNames[218] = "objbouncer";
	global.__objectNames[219] = "objbullet";
	global.__objectNames[220] = "objdashfish";
	global.__objectNames[221] = "objdebris";
	global.__objectNames[222] = "partialdebris";
	global.__objectNames[223] = "objdebrisbouncer";
	global.__objectNames[224] = "objspark";
	global.__objectNames[225] = "objsmoke";
	global.__objectNames[226] = "objsmexp";
	global.__objectNames[227] = "objAirOut";
	global.__objectNames[228] = "objElExp";
	global.__objectNames[229] = "objmedexp";
	global.__objectNames[230] = "objbigexp";
	global.__objectNames[231] = "objredwarning";
	global.__objectNames[232] = "objelectric";
	global.__objectNames[233] = "objsmoker";
	global.__objectNames[234] = "objStatic";
	global.__objectNames[235] = "objCutFlash";
	global.__objectNames[236] = "objredlaser";
	global.__objectNames[237] = "objredblob";
	global.__objectNames[238] = "objredwave";
	global.__objectNames[239] = "objPipe";
	global.__objectNames[240] = "objPipeInit";
	global.__objectNames[241] = "objPipeFollower";
	global.__objectNames[242] = "objLavaFall";
	global.__objectNames[243] = "objLavaDrops";
	global.__objectNames[244] = "sparkables";
	global.__objectNames[245] = "objTDRoom";
	global.__objectNames[246] = "objTDWalls";
	global.__objectNames[247] = "objCpuTable";
	global.__objectNames[248] = "objCpu";
	global.__objectNames[249] = "objServer";
	global.__objectNames[250] = "objMouse";
	global.__objectNames[251] = "objRack";
	global.__objectNames[252] = "objEquipRack";
	global.__objectNames[253] = "objCables1";
	global.__objectNames[254] = "objCables2";
	global.__objectNames[255] = "objSockets";
	global.__objectNames[256] = "objElArc";
	global.__objectNames[257] = "objElSpark";
	global.__objectNames[258] = "objSuperFG";
	global.__objectNames[259] = "objProxyEgg";
	global.__objectNames[260] = "objSuperEgg";
	global.__objectNames[261] = "objSuperSonic";
	global.__objectNames[262] = "objChargeBalls";
	global.__objectNames[263] = "objEvilChargeBalls";
	global.__objectNames[264] = "objSparkly";
	global.__objectNames[265] = "objFullSparkly";
	global.__objectNames[266] = "objSuperGrass";
	global.__objectNames[267] = "objLimitedGrass";
	global.__objectNames[268] = "objDust";
	global.__objectNames[269] = "objFullDust";
	global.__objectNames[270] = "objCraft3";
	global.__objectNames[271] = "objSuprectile";
	global.__objectNames[272] = "objSuperExplosion";
	global.__objectNames[273] = "objNuke";
	global.__objectNames[274] = "objSuperHit";
	global.__objectNames[275] = "objElectricWall";
	global.__objectNames[276] = "objElectricWarning";
	global.__objectNames[277] = "objSuperRingGet";
	global.__objectNames[278] = "objSuperRing";
	global.__objectNames[279] = "objRainEnd";
	global.__objectNames[280] = "objFrontEnd";
	global.__objectNames[281] = "objSmokeEnd";
	global.__objectNames[282] = "objSonicEnd1";
	global.__objectNames[283] = "objTailsEnd1";
	global.__objectNames[284] = "objBubbleEnd";
	global.__objectNames[285] = "makeDance";
	global.__objectNames[286] = "danceTa";
	global.__objectNames[287] = "danceSo";
	global.__objectNames[288] = "danceStatic";
	global.__objectNames[289] = "objFirePlace";
	global.__objectNames[290] = "objSingleRain";
	global.__objectNames[291] = "objRainHit";
	global.__objectNames[292] = "objEggGanon";
	global.__objectNames[293] = "balls";
	global.__objectNames[294] = "mtline";
	global.__objectNames[295] = "bike";
	global.__objectNames[296] = "objIntroHurt";
	global.__objectNames[297] = "objIntroSonic";
	global.__objectNames[298] = "objIntroEmerald";
	global.__objectNames[299] = "introgenerator";
	global.__objectNames[300] = "objBkSquare";
	global.__objectNames[301] = "mtpoint";
	global.__objectNames[302] = "fakebike";
	global.__objectNames[303] = "objBG";
	global.__objectNames[304] = "objBolt";
	global.__objectNames[305] = "objBranch";
	global.__objectNames[306] = "objCloudMaker";
	global.__objectNames[307] = "objCloud";
	global.__objectNames[308] = "viper";
	global.__objectNames[309] = "objVipFlame";
	global.__objectNames[310] = "objVipRocket";
	global.__objectNames[311] = "objIntroRing";
	global.__objectNames[312] = "objTuText";
	global.__objectNames[313] = "objQuitWarning";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
