__view_set( e__VW.XView, 0, 0 );
__view_set( e__VW.YView, 0, 0 );

// intro_finish() destroys every instance before creating the menu, including
// objRingCounter. Recreate it instead of dereferencing an absent singleton.
var ring_counter = instance_find(objRingCounter, 0);
if (!instance_exists(ring_counter))
    ring_counter = instance_create(0, 0, objRingCounter);
ring_counter.showRings = 0;

nSound[0]="sndAfterBurner.wav";
nSound[1]="sndAfterBurnerLong.wav";
nSound[2]="sndAfterBurnerStop.wav";
nSound[3]="sndAfterBurnerStop2.wav";
nSound[4]="sndArmChange.wav";
nSound[5]="sndBeep.wav";
nSound[6]="sndBigGun.wav";
nSound[7]="sndBigSplash.wav";
nSound[8]="sndBlob.wav";
nSound[9]="sndBlth.wav";
nSound[10]="sndBooster.wav";
nSound[11]="sndBreakDown.wav";
nSound[12]="sndBreakDownBuffer.wav";
nSound[13]="sndBubble.wav";
nSound[14]="sndC.wav";
nSound[15]="sndChainSewer.wav";
nSound[16]="sndCharge.wav";
nSound[17]="sndCharge2.wav";
nSound[18]="sndChopper.wav";
nSound[19]="sndChopperScream.wav";
nSound[20]="sndClank.wav";
nSound[21]="sndClick.wav";
nSound[22]="sndClink.wav";
nSound[23]="sndClosePush.wav";
nSound[24]="sndCrash.wav";
nSound[25]="sndCrush.wav";
nSound[26]="sndCutter.wav";
nSound[27]="sndDarkDestroy.wav";
nSound[28]="sndDarkHum.wav";
nSound[29]="sndDarkO.wav";
nSound[30]="sndDarkness.wav";
nSound[31]="sndDash.wav";
nSound[32]="sndDeath.wav";
nSound[33]="sndDoll.wav";
nSound[34]="sndDollLaser1.wav";
nSound[35]="sndDollLaser2.wav";
nSound[36]="sndDoom.wav";
nSound[37]="sndDoorClose.wav";
nSound[38]="sndDoorOpen.wav";
nSound[39]="sndDrown.wav";
nSound[40]="sndElectric1.wav";
nSound[41]="sndElectric2.wav";
nSound[42]="sndElevator.wav";
nSound[43]="sndElevatorSetup.wav";
nSound[44]="sndElevatorStop.wav";
nSound[45]="sndEngine.wav";
nSound[46]="sndEngine2.wav";
nSound[47]="sndEngineStart.wav";
nSound[48]="sndExplosion.wav";
nSound[49]="sndExtend.wav";
nSound[50]="sndFastCharge.wav";
nSound[51]="sndFinalBoom.wav";
nSound[52]="sndFlame.wav";
nSound[53]="sndFlap.wav";
nSound[54]="sndFlashOut.wav";
nSound[55]="sndFomp.wav";
nSound[56]="sndForceBounce.wav";
nSound[57]="sndGetUp.wav";
nSound[58]="sndGun.wav";
nSound[59]="sndGunFast.wav";
nSound[60]="sndGunstar1.wav";
nSound[61]="sndGunstar2.wav";
nSound[62]="sndGunstar3.wav";
nSound[63]="sndHit.wav";
nSound[64]="sndIdle.wav";
nSound[65]="sndJoinMe.wav";
nSound[66]="sndJump.wav";
nSound[67]="sndLand1.wav";
nSound[68]="sndLand2.wav";
nSound[69]="sndLavaAmb1.wav";
nSound[70]="sndLavaAmb2.wav";
nSound[71]="sndLavaBlob.wav";
nSound[72]="sndLavaFall.wav";
nSound[73]="sndLavaFizz.wav";
nSound[74]="sndLoseRing.wav";
nSound[75]="sndMercury.wav";
nSound[76]="sndMetal1.wav";
nSound[77]="sndMetal2.wav";
nSound[78]="sndMetal3.wav";
nSound[79]="sndMetalScrape.wav";
nSound[80]="sndMiniGun.wav";
nSound[81]="sndNonRythmic.wav";
nSound[82]="sndOoze1.wav";
nSound[83]="sndOoze2.wav";
nSound[84]="sndOoze3.wav";
nSound[85]="sndOoze4.wav";
nSound[86]="sndPause.wav";
nSound[87]="sndPop.wav";
nSound[88]="sndPull.wav";
nSound[89]="sndPush.wav";
nSound[90]="sndQuake.wav";
nSound[91]="sndRain.wav";
nSound[92]="sndRaze.wav";
nSound[93]="sndRecovery.wav";
nSound[94]="sndRedBlob.wav";
nSound[95]="sndRedLaser.wav";
nSound[96]="sndRedLaserCharge.wav";
nSound[97]="sndRedWave.wav";
nSound[98]="sndRing.wav";
nSound[99]="sndRoar.wav";
nSound[100]="sndRoar2.wav";
nSound[101]="sndRobot.wav";
nSound[102]="sndRoll.wav";
nSound[103]="sndRunning.wav";
nSound[104]="sndShaft.wav";
nSound[105]="sndShield.wav";
nSound[106]="sndShieldFailure.wav";
nSound[107]="sndShockWave.wav";
nSound[108]="sndShortDark.wav";
nSound[109]="sndSnipe.wav";
nSound[110]="sndSpin.wav";
nSound[111]="sndSpinDown.wav";
nSound[112]="sndSpinUp.wav";
nSound[113]="sndSpjoing.wav";
nSound[114]="sndSplash.wav";
nSound[115]="sndSplashStep.wav";
nSound[116]="sndStop.wav";
nSound[117]="sndSunshine.wav";
nSound[118]="sndSurprise.wav";
nSound[119]="sndSurround.wav";
nSound[120]="sndTails0.wav";
nSound[121]="sndTails1.wav";
nSound[122]="sndTails2.wav";
nSound[123]="sndTails3.wav";
nSound[124]="sndTails4.wav";
nSound[125]="sndTails5.wav";
nSound[126]="sndTailsFly.wav";
nSound[127]="sndTargetConfirm.wav";
nSound[128]="sndThunder1.wav";
nSound[129]="sndThunder2.wav";
nSound[130]="sndThunder3.wav";
nSound[131]="sndThunder4.wav";
nSound[132]="sndTimer.wav";
nSound[133]="sndTurbulence.wav";
nSound[134]="sndType.wav";
nSound[135]="sndUltima.wav";
nSound[136]="sndUnPush.wav";
nSound[137]="sndUnWater.wav";
nSound[138]="sndViper.wav";
nSound[139]="sndWetFall.wav";
nSound[140]="sndWetLand.wav";
nSound[141]="sndWhitenoise.wav";
nSound[142]="sndWilhelm.wav";
nSound[143]="sndWind.wav";
nSounds=144;

__background_set_colour( c_black );
audio_play_sound(FoxFace, 10, true);
constant = 50;
rackAngle = constant;
charge = 0.5;
for(a=0; a<8; a+=1)
    {
    __background_set( e__BG.Visible, a, 0 );
    __background_set( e__BG.HSpeed, a, 0 );
    __background_set( e__BG.VSpeed, a, 0 );
    __background_set( e__BG.Alpha, a, 1 );
    __background_set( e__BG.Foreground, a, 0 );
    }
on = 0;
action_set_alarm(1, 0);
emeralds = 7;
action_move_to(32, 480-32);
timer = 0;
room_speed=30;

define_Emeralds();


emerald_t[0]="Start Game";
if(global.verticalSync)
    emerald_t[1]="Vsync: On";
else
    emerald_t[1]="Vsync: Off";
if(global.zeroRingMode)
    emerald_t[2]="Zero Ring Mode: On";
else
    emerald_t[2]="Zero Ring Mode: Off";
emerald_t[3]="Music Box";
emerald_t[4]="Sound Test";
emerald_t[5]="Credits";
emerald_t[6]="Quit";

a=0;  music_t[a]=0; music_f[a]="OpenedWay.ogg";
music_n[a]="The Opened Way";
a+=1; music_t[a]=0; music_f[a]="FoxFace.wav";
music_n[a]="Gypsy Foxface";
a+=1; music_t[a]=0; music_f[a]="Dass.ogg";
music_n[a]="UberMongo";
a+=1; music_t[a]=1; music_f[a]="Ingenious.mid";
music_n[a]="Ingenious";
a+=1; music_t[a]=0; music_f[a]="Invulnerability.ogg";
music_n[a]="Invulnerability On";
a+=1; music_t[a]=1; music_f[a]="Sulfur.mid";
music_n[a]="Io Sulfur Mine";
a+=1; music_t[a]=0; music_f[a]="FeistyOne1.ogg";
music_n[a]="Feisty One(Act1)";
a+=1; music_t[a]=0; music_f[a]="FeistyOne2.ogg";
music_n[a]="Feisty One(Act2)";
a+=1; music_t[a]=1; music_f[a]="OrSmovr.mid";
music_n[a]="Or Smovr Bos";
a+=1; music_t[a]=1; music_f[a]="ForBossen.mid";
music_n[a]="For Bossen";
a+=1; music_t[a]=1; music_f[a]="Samwedo.mid";
music_n[a]="Samwedo";
a+=1; music_t[a]=0; music_f[a]="MentalMachine.ogg";
music_n[a]="Mental Machine";
a+=1; music_t[a]=1; music_f[a]="Sunshine.mid";
music_n[a]="Can You Feel the Sunshine";
a+=1; music_t[a]=0; music_f[a]="SevenForce.ogg";
music_n[a]="Theme of Seven Force";
a+=1; music_t[a]=0; music_f[a]="MetalScratchin1.ogg";
music_n[a]="Metal Scratchin' 1";
a+=1; music_t[a]=0; music_f[a]="MetalScratchin2.ogg";
music_n[a]="Metal Scratchin' 2";
a+=1; music_t[a]=0; music_f[a]="Library.ogg";
music_n[a]="Terra vs Braig";
a+=1; music_t[a]=0; music_f[a]="SuperUltraViolet1.ogg";
music_n[a]="Super Ultra Violet 1";
a+=1; music_t[a]=0; music_f[a]="SuperUltraViolet2.ogg";
music_n[a]="Super Ultra Violet 2";
a+=1; music_t[a]=0; music_f[a]="LikeThis.ogg";
music_n[a]="A Ship Like This";
a+=1; music_t[a]=0; music_f[a]="Tails.ogg";
music_n[a]="Tails' Poem";
a+=1; music_t[a]=1; music_f[a]="YellowSpot.mid";
music_n[a]="A Spot in the Stairs";
a+=1; music_t[a]=1; music_f[a]="Timer.mid";
music_n[a]="Need Oxygen";

a+=1; musics=a;
option = 0;
acc = 0;
goalAngle = constant;
up = 0;
up = 1;
able = 1;
