radius = 12;
nx=0;
ny=-1;
ux=1;
uy=0;
gnd=0;
i=instance_create(x-32,y+16,balls);
i1=i;

i=instance_create(x+32,y+16,balls);
i2=i;
acc = 0.7;
lift = 0.3;
boost = 0.8;
boosting = 0;
boostgauge = 1;
maxboost = 30;
angsp = 0;
dir = 0;
lastDir = 0;
able = 1;
cx=0;
cy=0;
cb=0;
pcb=0;
soundloop(global.sndIdle);
soundloop(global.sndRunning);
// Start with a quiet running loop and an audible idle loop. Without explicit
// initial volumes both loops played at full volume until the first input.
var bikeVolume = variable_global_exists("maxVolume") ? global.maxVolume : 0.85;
soundvolume(global.sndRunning,0);
soundvolume(global.sndIdle,bikeVolume);
idle = 1;
gear = 0;
interval = 20;
freq = 0.05;
blink = 0;
sonicImg = 0;
sonicBase = 0;
correction = 0;
haltBoost = 0;
mySonic = 1;
sonicBaseTimer = 0;
blinkTimer = 0;
